# Site settings
title:          Test Site for Day of DH
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chesterhow.github.io"

# Author
author:
  name:         Deborah Caldwell 
  url:          https://deborahcaldwell.github.io/dayofdh/
  email:        deborah.caldwell@unt.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
